"English":
- 'src/en/**'

"Russian":
- 'src/ru/**'

"Ukrainian":
- 'src/ua/**'

"Scripts":
- 'scripts/**'

# I have tried making this robust (tm) using wildcards so many times but github docs for the labeler SUUUUCK. If you got time to figure it out please do it I give up.
# Welcome to the mega labeler.
"Design":
# General design
- 'src/en/site-14/core-design/**'

# Department design
- 'src/en/site-14/departments/atmos/*'

